---
# PiVT Configuration File

# The three dashes at the start of the file are important, please leave them in!

# Folder where video files can be found (--folder). Absolute paths recommended!
videofolder: /videos

# Port for the network interface to PiVTDesktop (--port).
port: 9815

# Additional arguments to supply to OMXPlayer (--omxargs)
omxargs: --nodeinterlace --win '0 0 1920 1080' --adev local

# Path to log file
logfile: pivtlog.log

# Remaining configuration items are internal and can probably remain as-is

# Path to OMXPlayer binary
omxplayer: /usr/bin/omxplayer

# Period to update internal file list in seconds
listcycletime: 5

# The dots are important, please leave them here
...
